- name: Update Debian servers
  hosts: myhosts
  become: true  # Run tasks with sudo privileges
  gather_facts: true # We need the ansible_os_family fact
  tasks:
    - name: Update apt cache on Debian systems
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: List upgradable packages
      ansible.builtin.command:
        cmd: "apt list --upgradable"
      register: upgradable_packages
      changed_when: false # This command doesn't change anything

    - name: Display upgradable packages
      ansible.builtin.debug:
        var: upgradable_packages.stdout_lines
      when: ansible_os_family == "Debian"
