- name: Upgrade Debian packages
  hosts: myhosts
  become: true
  gather_facts: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: yes
      when: ansible_os_family == "Debian"
